// Presets de labels prêts à l'emploi
// Les items n'ont pas d'id — on leur en attribue un au moment du chargement

export const LABEL_PRESETS = [
  {
    id: 'mariage',
    name: 'Mariage',
    description: 'Relation au couple',
    items: [
      { name: 'Marié(e)',              color: '#EC4899' },
      { name: 'Témoin',               color: '#EF4444' },
      { name: 'Clergé',               color: '#8B5CF6' },
      { name: 'Parent',               color: '#3B82F6' },
      { name: 'Frère / Sœur',         color: '#14B8A6' },
      { name: 'Famille',              color: '#22C55E' },
      { name: 'Ami proche',           color: '#F97316' },
      { name: 'Cousin proche',        color: '#EAB308' },
      { name: 'Ami',                  color: '#6B7280' },
      { name: 'Cousin',               color: '#047857' },
      { name: 'Copain',               color: '#6B7280' },
      { name: 'Cousin éloigné',       color: '#B45309' },
      { name: 'Ami des parents',      color: '#6B7280' },
      { name: 'Ami des frères/sœurs', color: '#6B7280' },
    ],
  },
  {
    id: 'chorale',
    name: 'Chorale',
    description: 'Voix et rôles',
    items: [
      { name: 'Chef de chœur',   color: '#EF4444' },
      { name: 'Chantre',         color: '#8B5CF6' },
      { name: 'Soprano',         color: '#EC4899' },
      { name: 'Alto',            color: '#F97316' },
      { name: 'Ténor',           color: '#3B82F6' },
      { name: 'Basse',           color: '#0369A1' },
      { name: 'Instrumentiste',  color: '#22C55E' },
      { name: 'Non',             color: '#6B7280' },
    ],
  },
  {
    id: 'entreprise',
    name: 'Entreprise',
    description: 'Service ou fonction',
    items: [
      { name: 'Direction',    color: '#EF4444' },
      { name: 'Manager',      color: '#F97316' },
      { name: 'RH',           color: '#EAB308' },
      { name: 'Tech',         color: '#3B82F6' },
      { name: 'Commercial',   color: '#22C55E' },
      { name: 'Marketing',    color: '#EC4899' },
      { name: 'Client',       color: '#14B8A6' },
      { name: 'Partenaire',   color: '#8B5CF6' },
      { name: 'Prestataire',  color: '#6B7280' },
      { name: 'VIP',          color: '#B45309' },
    ],
  },
  {
    id: 'conference',
    name: 'Conférence',
    description: 'Statut du participant',
    items: [
      { name: 'Conférencier', color: '#EF4444' },
      { name: 'Modérateur',   color: '#F97316' },
      { name: 'Organisateur', color: '#8B5CF6' },
      { name: 'VIP',          color: '#B45309' },
      { name: 'Sponsor',      color: '#EAB308' },
      { name: 'Presse',       color: '#3B82F6' },
      { name: 'Staff',        color: '#14B8A6' },
      { name: 'Participant',  color: '#6B7280' },
    ],
  },
  {
    id: 'bapteme',
    name: 'Baptême',
    description: "Relation à l'enfant",
    items: [
      { name: 'Parrain',           color: '#3B82F6' },
      { name: 'Marraine',          color: '#EC4899' },
      { name: 'Famille proche',    color: '#22C55E' },
      { name: 'Famille éloignée',  color: '#14B8A6' },
      { name: 'Ami de la famille', color: '#F97316' },
      { name: 'Paroisse',          color: '#8B5CF6' },
    ],
  },
  {
    id: 'soiree',
    name: 'Soirée',
    description: "Relation à l'hôte",
    items: [
      { name: 'Famille',      color: '#22C55E' },
      { name: 'Ami proche',   color: '#F97316' },
      { name: 'Ami',          color: '#3B82F6' },
      { name: 'Collègue',     color: '#8B5CF6' },
      { name: 'Voisin',       color: '#14B8A6' },
      { name: 'Connaissance', color: '#6B7280' },
    ],
  },
  {
    id: 'association',
    name: 'Association',
    description: "Rôle dans l'association",
    items: [
      { name: 'Bureau',        color: '#EF4444' },
      { name: 'Membre actif',  color: '#3B82F6' },
      { name: 'Bénévole',      color: '#22C55E' },
      { name: 'Partenaire',    color: '#8B5CF6' },
      { name: 'Sponsor',       color: '#EAB308' },
      { name: 'Invité',        color: '#6B7280' },
    ],
  },
]
